### ISSUE TITLE
Determinar tareas a realizar para el proyecto

### ISSUE THREAD

**Issue by antbaeriv** [AntJesJM/Monparti#12]
Tras debatir en grupo se plasmarán las principales tareas a realizar para el proyecto en un documento de texto.
Una vez acordadas y escritas, se desglosarán en tareas más sencillas.
Finalmente estas tareas sencillas se incluirán en GitHub como issues del proyecto.
Cada issue será asignada a uno o varios miembros del grupo según se haya acordado.

**Comment by jesureda** [comment]
Tras debatir en grupo se plasmarán las principales tareas a realizar para el proyecto en un documento de texto.
Una vez acordadas y escritas, se desglosarán en tareas más sencillas.
Finalmente estas tareas sencillas se incluirán en GitHub como issues del proyecto.
Cada issue será asignada a uno o varios miembros del grupo según se haya acordado.
